=== meWarehouse/javaweb/day02 java解析xml/bin/com/kc/jaxp/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/test" 
		xmlns:tns="http://www.example.org/test"
			elementFormDefault="qualified">

	<xs:element name="people">
		<xs:complexType>
			<xs:sequence>
				<!-- teacher student boos -->
				<xs:element name="teacher">
					<!-- name(string) age(integer 0-120) salary(decimal) address(string) -->
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string" /><!-- name -->
							<xs:element name="age">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="0" />
										<xs:maxInclusive value="120" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element><!-- age -->
							<xs:element name="salary" type="xs:decimal" /><!-- salary -->
							<xs:element name="address" type="xs:string" maxOccurs="unbounded" /><!-- 
								address -->
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<!-- student -->
				<xs:element name="student" maxOccurs="unbounded">
					<!-- name(string) age(integer) numberid(positiveInteger) course(string 
						max 3) -->
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string" /><!-- name -->
							<xs:element name="age">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="0" />
										<xs:maxInclusive value="120" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element><!-- age -->
							<xs:element name="numberid" type="xs:positiveInteger" />
							<xs:element name="course" type="xs:string" maxOccurs="3" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


</xs:schema>

=== meWarehouse/javaweb/day02 java解析xml/src/com/kc/jaxp/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><people xmlns="http://www.example.org/test" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/test test.xsd">
	<teacher>
		<name>一个</name>
		<age>23</age>
		<salary>10000.00</salary>
		<address>不知道</address>
	</teacher>
	<student>
		<name>一一</name>
		<age>3</age>
		<numberid>12</numberid>
		<course>javaee</course>
		<course>jsp</course>
		<course>javase</course>
	</student>
	<student>
		<name>er号</name>
		<age>20</age>
		<numberid>0112</numberid>
		<course>C</course>
		<course>Python</course>
		<course>c++</course>
	</student>

<备注>天天学习，好好向上！！！</备注></people>
